---
# tasks file for ansible-role-gradle

- name: "Check gradle version is present"
  stat:
    path: "{{ gradle_link }}"
  register: gradle_present

- name: "Check gradle version is present"
  shell: "{{ gradle_link }} -v | grep {{ gradle_version }}"
  changed_when: false
  register: gradle_version_check
  when: gradle_present.stat.exists

- block:

  - name: "Install unzip"
    package:
      name: unzip
      state: latest

  - name: "Download"
    get_url:
      url: "{{ gradle_download_url }}"
      dest: "{{ gradle_download }}"
      checksum: "{{ gradle_checksum }}"

  - name: "Extract Gradle {{ gradle_version }}"
    unarchive:
      src: "{{ gradle_download }}"
      dest: "{{ gradle_base_dir }}"
      remote_src: True

  - name: "Add gradle symlink to path"
    file:
      src: "{{ gradle_base_dir }}/{{ gradle_extract_dir }}/bin/gradle"
      dest: "{{ gradle_link }}"
      owner: root
      group: root
      state: link

  - name: "Validate Gradle version"
    shell: "{{ gradle_link }} -v | grep {{ gradle_version }}"
    register: gradle_ver

  - fail:
      msg: "Seems to be gradle {{ gradle_version }} is missing ... aborting"
    when: gradle_ver.rc != 0

  when: not gradle_present.stat.exists

- name: "Validate Gradle version"
  shell: "{{ gradle_link }} -v | grep {{ gradle_version }}"
  changed_when: False
  register: gradle_ver

- debug:
    msg: "Gradle {{ gradle_version }} is installed"
  when: gradle_ver.rc == 0
